### ISSUE TITLE
InvalidCacheBackendError at /

### ISSUE THREAD

**Issue by liqinsg** [diegogslomp/django-monitor#6]
When I browse to the http://localhost:8000 is shows the following error
InvalidCacheBackendError at /

Could not find backend 'django_redis.cache.RedisCache': cannot import name 'six' from 'django.utils' (/usr/local/lib/python3.8/site-packages/django/utils/__init__.py)

Request Method: 	GET
Request URL: 	http://10.11.104.19:8000/
Django Version: 	3.0
Exception Type: 	InvalidCacheBackendError
Exception Value: 	

Could not find backend 'django_redis.cache.RedisCache': cannot import name 'six' from 'django.utils' (/usr/local/lib/python3.8/site-packages/django/utils/__init__.py)

Exception Location: 	/usr/local/lib/python3.8/site-packages/django/core/cache/__init__.py in _create_cache, line 52
Python Executable: 	/usr/local/bin/python
Python Version: 	3.8.0
Python Path: 	

['/usr/src/app',
 '/usr/local/bin',
 '/usr/local/lib/python38.zip',
 '/usr/local/lib/python3.8',
 '/usr/local/lib/python3.8/lib-dynload',
 '/usr/local/lib/python3.8/site-packages']

Server time: 	Tue, 10 Dec 2019 07:57:24 -0300

**Comment by diegogslomp** [comment]
Hello,

I removed redis cache, fixed the staticfiles tag from base template and removed the SESSION_COOKIE_SECURE to be able to login without https configured. Please try to update using `git pull --recurse-submodules` updating the monitor app too. Any problems please be in touch.

**Comment by liqinsg** [comment]
Got the following error after pull 
![2019-12-11-114748](https://user-images.githubusercontent.com/32053924/70590070-84b71e00-1c0c-11ea-926c-fb8866b92a64.png)

**Comment by diegogslomp** [comment]
I commented out production vars from settings, if you need anything it could be changed in main/settings file. In the future I'll check the cache and production settings properly. Please pull and check if it's ok.

**Comment by diegogslomp** [comment]
I'm closing this threat, any problems please get in touch. For the next latest release, sqlite and docker run will be removed and docker-compose with postgres and nginx will be the default. If using docker run and sqlite keep using the v.0.3.4 version.
